#!/usr/bin/env ansible-playbook
---
- name: ceph cluster host prep
  hosts: ceph
  become: yes

  roles:
    - aws_ntp
    - fips
    - firewall
    - influx_repo

  post_tasks:
    - name: Chek for epel repo
      shell: >
        rc=$(yum-config-manager | egrep "\[epel\]");
        if [ -z "$rc" ];
        then
          echo "not enabled";
        else
          echo "enabled";
        fi
      register: result
      ignore_errors: yes
    - name: Enable epel repo
      command: yum-config-manager --enable epel
      when: result.stdout == "not enabled"
    - name: Install ceph repo pkg
      yum:
        name: centos-release-ceph-luminous
        state: present

- name: Admin
  hosts: admin
  gather_facts: no
  tasks:
    - user:
        name: ceph
        generate_ssh_key: yes
        ssh_key_bits: 2048
        shell: /bin/bash
      register: result
    - set_fact:
        ceph_ssh_pubkey: "{{ result.ssh_public_key }}"
    - authorized_key:
        user: ceph
        state: present
        key: "{{ ceph_ssh_pubkey }}"

    - debug:
        var: ceph_ssh_pubkey

    - copy:
        dest: /etc/sudoers.d/ceph
        owner: root
        group: root
        mode: '0600'
        content: "ceph ALL=(ALL:ALL) NOPASSWD:ALL"

- name: Install ceph user
  hosts: ceph:!admin
  gather_facts: yes
  tasks:
    - debug:
        var: hostvars[groups['admin'][0]]['ceph_ssh_pubkey']
    - user:
        name: ceph
        shell: /bin/bash
    - authorized_key:
        user: ceph
        state: present
        key: "{{ hostvars[groups['admin'][0]]['ceph_ssh_pubkey'] }}"
    - copy:
        dest: /etc/sudoers.d/ceph
        owner: root
        group: root
        mode: '0600'
        content: "ceph ALL=(ALL:ALL) NOPASSWD:ALL"

- name: install ceph base
  hosts: mon:osd:mds
  gather_facts: no
  tasks:
    - yum:
        name: ceph
        state: present
    - user:
        name: ceph

- name: RADOS gateway
  hosts: rgw
  gather_facts: no
  tasks:
    - yum:
        name: ceph-radosgw
        state: present

- name: Install utils
  hosts: admin
  gather_facts: no
  tasks:
    - yum:
        name:
          - python-pip
          - python-boto3
          - ansible
    - pip:
        name: ceph-deploy
    - copy:
        src=aws_ceph_util.py
        dest=/usr/local/bin/
        mode=0755
    - copy:
        src=osd_cr_template.py
        dest=/usr/local/bin/
        mode=0755
    - copy:
        src=inventory
        dest=/etc/ansible/
