#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - always

  vars:
    cluster_name: "ceph"
    key_name: "n62-test"
    instance_type: "t2.large"
    osd_instance_type: "i3.large"
    security_groups:
      - sg-21649b45
      - sg-5d4daf39
    # osd_volumes:
    #   - device_name: /dev/sdb
    #     volume_type: io1
    #     iops: 1000
    #     volume_size: 400
    #     delete_on_termination: yes
    #   - device_name: /dev/sdc
    #     volume_type: io1
    #     iops: 1000
    #     volume_size: 400
    #     delete_on_termination: yes
    #   - device_name: /dev/sdd
    #     volume_type: io1
    #     iops: 1000
    #     volume_size: 400
    #     delete_on_termination: yes
    osd_volumes: ~

  tasks:
    - name: Find VPC
      ec2_vpc_net_facts:
        filters:
          "tag:Name": N62
      register: results
    - set_fact:
        vpc: "{{ (results.vpcs | first).id  }}"

    - name: Find subnet
      ec2_vpc_subnet_facts:
        filters:
          vpc-id: "{{ vpc  }}"
          "tag:Name": CephStorage
      register: results
    - set_fact:
        ceph_subnet: "{{ (results.subnets | first).id }}"
        ceph_subnets: "{{ (results.subnets|map(attribute='id'))|sort|list  }}"
    - set_fact:
        ceph_subnet_a: "{{ ceph_subnets[0] }}"
        ceph_subnet_b: "{{ ceph_subnets[1] }}"

    - debug:
        var: ceph_subnet_a

    - name: Query AMI ID
      ec2_ami_facts:
        filters:
          name: "spel-minimal-centos-7-hvm-*"
        #owner: self
      register: results
    - set_fact:
        ami: "{{ (results.images | sort(attribute='creation_date') | last).image_id  }}"

    - name: Launch admin Instance
      ec2:
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ ceph_subnet_a  }}"
        group_id: "{{ security_groups  }}"
        instance_type: "{{  instance_type  }}"
        image: "{{ami}}"
        wait: yes
        instance_tags:
          Name: ceph-admin
          Cluster: "{{ cluster_name }}"
        count_tag:
          Name: ceph-admin
        exact_count: 1
        instance_profile_name: CI-vpc-N62
      register: results

    - name: Launch monitor Instance
      ec2:
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ item  }}"
        group_id: "{{ security_groups  }}"
        instance_type: "{{  instance_type  }}"
        image: "{{ami}}"
        wait: yes
        instance_tags:
          Name: ceph-mon
          Cluster: "{{ cluster_name }}"
        count_tag:
          Name: ceph-mon
        exact_count: 2
      loop:
        - "{{ ceph_subnet_a }}"
        - "{{ ceph_subnet_b }}"
      register: results

    - name: Launch OSD Instances
      ec2:
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ item  }}"
        group_id: "{{ security_groups  }}"
        instance_type: "{{  osd_instance_type  }}"
        image: "{{ami}}"
        wait: yes
        instance_tags:
          Name: ceph-osd
          Cluster: "{{ cluster_name }}"
        count_tag:
          Name: ceph-osd
        exact_count: 8
        volumes: "{{ osd_volumes }}"
      loop:
        - "{{ ceph_subnet_a }}"
        - "{{ ceph_subnet_b }}"
      register: results

    - name: Launch RGW Instances
      ec2:
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ item  }}"
        group_id: "{{ security_groups  }}"
        instance_type: "{{  instance_type  }}"
        image: "{{ami}}"
        wait: yes
        instance_tags:
          Name: ceph-rgw
          Cluster: "{{ cluster_name }}"
        count_tag:
          Name: ceph-rgw
        exact_count: 2
      loop:
        - "{{ ceph_subnet_a }}"
        - "{{ ceph_subnet_b }}"
      register: results

    - name: Launch MDS Instances
      ec2:
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ item  }}"
        group_id: "{{ security_groups  }}"
        instance_type: "{{  instance_type  }}"
        image: "{{ami}}"
        wait: yes
        instance_tags:
          Name: ceph-mds
          Cluster: "{{ cluster_name }}"
        count_tag:
          Name: ceph-mds
        exact_count: 1
      loop:
        - "{{ ceph_subnet_a }}"
        - "{{ ceph_subnet_b }}"
      register: results

    - name: Launch client Instance
      ec2:
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ ceph_subnet  }}"
        group_id: "{{ security_groups  }}"
        instance_type: "{{  instance_type  }}"
        image: "{{ami}}"
        wait: yes
        instance_tags:
          Name: ceph-client
          Cluster: "{{ cluster_name }}"
        count_tag:
          Name: ceph-client
        exact_count: 1
      loop:
        - "{{ ceph_subnet_a }}"
        - "{{ ceph_subnet_b }}"
      register: results
