#!/usr/bin/env ansible-playbook
---
- name: ceph cluster host prep
  hosts: ceph
  become: yes

  handlers:
    - name: reboot
      shell: sleep 5 && reboot
      async: 1
      poll: 0
      ignore_errors: yes
      notify: wait for boot
    - name: wait for boot
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300

  roles:
    - aws_ntp
    - fips
    - firewall

  post_tasks:
    - name: Chek for epel repo
      shell: rc=$(yum-config-manager | egrep "\[epel\]"); if [ -z "$rc" ]; then echo "not enabled"; else echo "enabled"; fi
      register: result
      ignore_errors: yes
    - name: Enable epel repo
      command: yum-config-manager --enable epel
      when: result.stdout == "not enabled"
    - name: Install ceph repo pkg
      yum:
        name: centos-release-ceph-luminous
        state: present

- name: install ceph base
  hosts: mon:osd:mds
  gather_facts: no

  tasks:
    - yum:
        name: ceph
        state: present

- name:
  hosts: rgw
  gather_facts: no
  tasks:
    - yum:
      name: ceph-radosgw
      state: present