plugin: aws_ec2
regions:
  - us-gov-west-1

filters:
  vpc-id: vpc-11006274
  tag:Cluster: ceph
  instance-state-name: running

hostnames:
  - private-dns-name

groups:
  ceph: "tags['Name'].startswith('ceph')"
  osd: "tags['Name'].endswith('osd')"
  mon: "tags['Name'].endswith('mon')"
  mds: "tags['Name'].endswith('mds')"
  rgw: "tags['Name'].endswith('rgw')"
  client: "tags['Name'].endswith('client')"
